package com.bowltrack.ui.settings.calibration

import android.graphics.BitmapFactory
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.RangeSlider
import androidx.compose.material3.SliderDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.bowltrack.data.prefs.DetectionPreferences
import com.bowltrack.python.PythonBridge
import com.bowltrack.ui.components.GlassCard
import com.bowltrack.ui.components.PrimaryButton
import com.bowltrack.ui.components.SecondaryButton
import com.bowltrack.ui.theme.AccentMint
import com.bowltrack.ui.theme.LocalTypographyExtras
import com.bowltrack.video.VideoFrame
import com.bowltrack.video.VideoFrameExtractor
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

/** Which colour the screen is calibrating today. */
enum class CalibrationTarget { Pin, Car }

/**
 * HSV calibration screen.
 *
 * Lets the user tweak three OpenCV ranges (H, S, V) with `RangeSlider`s
 * while seeing the resulting binary mask painted live over the most
 * recent recording's first frame. The preview is generated by Python
 * via [PythonBridge.renderHsvMaskPreview], which returns PNG bytes
 * the screen decodes locally.
 *
 * Layout: top row = preview, bottom = three range sliders + Save /
 * Reset buttons. The save action persists to [DetectionPreferences]
 * and pops the screen.
 *
 * Pin uses a single H range; the car target uses two with the same
 * S/V to handle the hue ring wrap that "red" needs. We keep that
 * detail invisible to the user — they see one set of sliders for
 * either target and the screen synthesises both halves of the hue
 * range under the hood when needed.
 */
@Composable
fun ColorCalibrationScreen(
    target: CalibrationTarget,
    onBack: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val prefs = remember(context) { DetectionPreferences(context.applicationContext) }
    val settings by prefs.flow.collectAsState(initial = null)

    var hLo by remember { mutableStateOf(0f) }
    var hHi by remember { mutableStateOf(179f) }
    var sLo by remember { mutableStateOf(0f) }
    var sHi by remember { mutableStateOf(255f) }
    var vLo by remember { mutableStateOf(0f) }
    var vHi by remember { mutableStateOf(255f) }
    var initialised by remember { mutableStateOf(false) }

    // Seed the sliders from persisted settings the first time we have
    // them. Subsequent flow emissions do not stomp on user edits in
    // this screen — they would surprise the user mid-drag.
    LaunchedEffect(settings) {
        val current = settings ?: return@LaunchedEffect
        if (initialised) return@LaunchedEffect
        val ranges = when (target) {
            CalibrationTarget.Pin -> current.pinRanges
            CalibrationTarget.Car -> current.carRanges
        }
        // First range supplies H/S/V seeds. The "wrap-around" extra
        // range (car only) is rebuilt on save based on the chosen H.
        val seed = ranges.first()
        hLo = seed[0].toFloat(); sLo = seed[1].toFloat(); vLo = seed[2].toFloat()
        hHi = seed[3].toFloat(); sHi = seed[4].toFloat(); vHi = seed[5].toFloat()
        initialised = true
    }

    // Sample frame: first decoded frame from the most recent video,
    // cached for the lifetime of the screen.
    var sampleFrame by remember { mutableStateOf<VideoFrame?>(null) }
    var sampleStatus by remember { mutableStateOf("Looking for a sample frame...") }

    LaunchedEffect(Unit) {
        val source = findMostRecentVideo(context.filesDir)
        if (source == null) {
            sampleStatus = "No video found in app-private storage. Record or import one to enable the live preview."
            return@LaunchedEffect
        }
        runCatching {
            withContext(Dispatchers.IO) {
                val first = VideoFrameExtractor(source).frames().firstOrNull()
                if (first == null) {
                    sampleStatus = "Could not decode a sample frame."
                } else {
                    sampleFrame = first
                    sampleStatus = "Preview from ${source.name}"
                }
            }
        }.onFailure { error ->
            sampleStatus = "Preview unavailable: ${error.message ?: error::class.java.simpleName}"
        }
    }

    // Recompute the masked preview whenever the user moves a slider
    // or a fresh sample frame arrives. We debounce only via the
    // launch-replace-on-change semantics of `LaunchedEffect`'s key
    // list — sliders fire a lot of events but Python decoding finishes
    // fast enough that we stay smooth.
    var previewBitmap by remember { mutableStateOf<android.graphics.Bitmap?>(null) }
    val activeRanges = remember(target, hLo, hHi, sLo, sHi, vLo, vHi) {
        composeRanges(target, hLo.toInt(), hHi.toInt(), sLo.toInt(), sHi.toInt(), vLo.toInt(), vHi.toInt())
    }
    LaunchedEffect(sampleFrame, activeRanges) {
        val frame = sampleFrame ?: return@LaunchedEffect
        runCatching {
            val bytes = PythonBridge.renderHsvMaskPreview(frame, activeRanges)
            BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
        }.onSuccess { bitmap ->
            previewBitmap = bitmap
        }
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
            .verticalScroll(rememberScrollState())
            .padding(horizontal = 20.dp)
            .padding(top = 12.dp, bottom = 24.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        Text(
            text = when (target) {
                CalibrationTarget.Pin -> "Pin colour"
                CalibrationTarget.Car -> "Car colour"
            },
            style = MaterialTheme.typography.displayMedium,
            color = MaterialTheme.colorScheme.onBackground,
        )
        Text(
            text = "Drag the sliders until your target stays mint and everything else dims out. Saved values feed the classical detector on the next analysis.",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )

        Box(
            modifier = Modifier
                .fillMaxWidth()
                .aspectRatio(16f / 9f)
                .clip(RoundedCornerShape(14.dp))
                .background(MaterialTheme.colorScheme.surface),
            contentAlignment = Alignment.Center,
        ) {
            val bitmap = previewBitmap
            if (bitmap != null) {
                androidx.compose.foundation.Image(
                    bitmap = bitmap.asImageBitmap(),
                    contentDescription = "Live HSV mask preview",
                    modifier = Modifier.fillMaxSize(),
                )
            } else {
                Text(
                    text = sampleStatus,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(16.dp),
                )
            }
        }

        GlassCard(modifier = Modifier.fillMaxWidth()) {
            Column {
                ChannelSlider(
                    label = "Hue (H)",
                    range = hLo..hHi,
                    valueRange = 0f..179f,
                    onChange = { l, h -> hLo = l; hHi = h },
                )
                Spacer(Modifier.height(12.dp))
                ChannelSlider(
                    label = "Saturation (S)",
                    range = sLo..sHi,
                    valueRange = 0f..255f,
                    onChange = { l, h -> sLo = l; sHi = h },
                )
                Spacer(Modifier.height(12.dp))
                ChannelSlider(
                    label = "Value (V)",
                    range = vLo..vHi,
                    valueRange = 0f..255f,
                    onChange = { l, h -> vLo = l; vHi = h },
                )
            }
        }

        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            PrimaryButton(
                text = "Save",
                onClick = {
                    val toPersist = activeRanges
                    scope.launch {
                        when (target) {
                            CalibrationTarget.Pin -> prefs.setPinRanges(toPersist)
                            CalibrationTarget.Car -> prefs.setCarRanges(toPersist)
                        }
                        onBack()
                    }
                },
                modifier = Modifier.weight(1f),
            )
            SecondaryButton(
                text = "Reset",
                onClick = {
                    val defaults = when (target) {
                        CalibrationTarget.Pin -> com.bowltrack.data.prefs.DEFAULT_PIN_RANGES
                        CalibrationTarget.Car -> com.bowltrack.data.prefs.DEFAULT_CAR_RANGES
                    }
                    val seed = defaults.first()
                    hLo = seed[0].toFloat(); sLo = seed[1].toFloat(); vLo = seed[2].toFloat()
                    hHi = seed[3].toFloat(); sHi = seed[4].toFloat(); vHi = seed[5].toFloat()
                },
                modifier = Modifier.weight(1f),
            )
        }
        SecondaryButton(
            text = "Cancel",
            onClick = onBack,
            modifier = Modifier.fillMaxWidth(),
        )
    }
}

/**
 * Builds the on-disk HSV range list from the slider state.
 *
 * For [CalibrationTarget.Pin] we emit the single user-tuned range.
 * For [CalibrationTarget.Car] we *also* emit a wrap-around range
 * automatically when the user picks a low hue (≤ 25), pairing it
 * with a 170-179 stub so red still works without the user knowing
 * the OpenCV hue ring exists.
 */
private fun composeRanges(
    target: CalibrationTarget,
    hLo: Int, hHi: Int,
    sLo: Int, sHi: Int,
    vLo: Int, vHi: Int,
): List<IntArray> {
    val primary = intArrayOf(hLo, sLo, vLo, hHi, sHi, vHi)
    if (target == CalibrationTarget.Pin) return listOf(primary)
    val wrapAround = hLo <= 25
    return if (wrapAround) {
        val secondary = intArrayOf(170, sLo, vLo, 179, sHi, vHi)
        listOf(primary, secondary)
    } else {
        listOf(primary)
    }
}

@Composable
private fun ChannelSlider(
    label: String,
    range: ClosedFloatingPointRange<Float>,
    valueRange: ClosedFloatingPointRange<Float>,
    onChange: (Float, Float) -> Unit,
) {
    Column {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.fillMaxWidth(),
        ) {
            Text(
                text = label,
                style = MaterialTheme.typography.bodyLarge,
                color = MaterialTheme.colorScheme.onSurface,
                modifier = Modifier.weight(1f),
            )
            Text(
                text = "${range.start.toInt()} – ${range.endInclusive.toInt()}",
                style = LocalTypographyExtras.current.monoMedium,
                color = AccentMint,
            )
        }
        RangeSlider(
            value = range,
            onValueChange = { onChange(it.start, it.endInclusive) },
            valueRange = valueRange,
            colors = SliderDefaults.colors(
                thumbColor = AccentMint,
                activeTrackColor = AccentMint,
                inactiveTrackColor = MaterialTheme.colorScheme.outline,
            ),
        )
    }
}

private fun findMostRecentVideo(filesDir: File): File? {
    val candidates = listOf(
        File(filesDir, "recordings"),
        File(filesDir, "imports"),
    ).flatMap { dir ->
        if (dir.isDirectory) dir.listFiles { f -> f.isFile && f.length() > 0L }?.toList().orEmpty()
        else emptyList()
    }
    return candidates.maxByOrNull { it.lastModified() }
}
