package com.bowltrack.data.db.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Top-level row representing one analysed run.
 *
 * Identity: a UUID generated when the session is persisted. We use a
 * string id rather than autogenerated long so the same id can survive
 * an export/import flow (M13 export bundle) without clashing with
 * other rows seeded from the same range.
 *
 * Storage layout: scalar fields only. The car path lives in a child
 * table ([PathPointRecord]) and the fallen pins live in another
 * ([FallenPinRecord]); both are foreign-keyed back here. That keeps
 * the [BowlingSession] row small and lets History queries skip the
 * heavy data until a detail view actually needs it.
 *
 * @property id Stable string identifier. UUID v4 in production; tests
 *              build their own.
 * @property videoPath Absolute path to the source video on disk.
 *                     Held as a plain string because the Room type
 *                     converter for `java.io.File` would just round-
 *                     trip through `absolutePath` anyway.
 * @property recordedAtMillis Wall-clock timestamp when the analysis
 *                            was saved.
 * @property durationSeconds Length of the analysed video.
 * @property totalPins, fallenPins Final score numerator / denominator.
 * @property analysisWidth, analysisHeight Resolution at which the
 *                                          Python pipeline analysed
 *                                          the frames. Carried
 *                                          forward so the saved
 *                                          replay overlay can scale
 *                                          path coordinates back into
 *                                          the player without
 *                                          re-probing the file.
 * @property yoloStatus, yoloInvocations Diagnostic snapshot from the
 *                                        run.
 * @property carColor, carYolo, carLk, carMissing Histogram of how the
 *                                                car centroid was
 *                                                resolved during
 *                                                analysis.
 * @property classicalMs, yoloMs Aggregate per-tier wall-clock CPU.
 */
@Entity(tableName = "bowling_session")
data class BowlingSession(
    @PrimaryKey val id: String,
    val videoPath: String,
    val recordedAtMillis: Long,
    val durationSeconds: Float,
    val totalPins: Int,
    val fallenPins: Int,
    val analysisWidth: Int,
    val analysisHeight: Int,
    val yoloStatus: String,
    val yoloInvocations: Int,
    val carColor: Int,
    val carYolo: Int,
    val carLk: Int,
    val carMissing: Int,
    val classicalMs: Float,
    val yoloMs: Float,
) {
    val scoreLabel: String get() = "$fallenPins / $totalPins"
}
