package com.bowltrack.data.db.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One pin-fall event belonging to a [BowlingSession].
 *
 * The composite key would be `(session_id, order)` but Room does not
 * tolerate composite keys on a relation of this shape gracefully, so
 * we expose an autogenerated long row id and add a unique index on
 * `(session_id, order)` to enforce the same invariant.
 */
@Entity(
    tableName = "fallen_pin_record",
    foreignKeys = [
        ForeignKey(
            entity = BowlingSession::class,
            parentColumns = ["id"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        Index(value = ["sessionId"]),
        Index(value = ["sessionId", "order"], unique = true),
    ],
)
data class FallenPinRecord(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0L,
    val sessionId: String,
    val order: Int,
    val pinId: Int,
    val frameIndex: Int,
    val timestampSeconds: Float,
)
